console.log(typeof void 0);
console.log(typeof null);
console.log(typeof true);
console.log(typeof 1);
console.log(typeof "foo");
console.log(typeof {});
console.log(typeof function() {});

var x;
console.log(typeof x);
x = null;
console.log(typeof x);
x = true;
console.log(typeof x);
x = 1;
console.log(typeof x);
x = "foo";
console.log(typeof x);
x = {};
console.log(typeof x);
x = function () {};
console.log(typeof x);
